import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import ClientRouteGuard from "@/features/shared/components/RedirectController";
import { Suspense } from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SAURON",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <AppRouterCacheProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    {/* 
                        wrapped in suspense because when using useSearchParams at the top level
                        without suspense can cause the entire build to deopt to client side rendering or throw build warnings
                    */}
                    <Suspense fallback={null}>
                        <ClientRouteGuard>
                            {children}
                        </ClientRouteGuard>
                    </Suspense>
                </body>
            </AppRouterCacheProvider>
        </html>
    );
}
