import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import ClientRouteGuard from "@/features/shared/components/RedirectController";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SAURON",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <AppRouterCacheProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <ClientRouteGuard>
                        {children}
                    </ClientRouteGuard>
                </body>
            </AppRouterCacheProvider>
        </html>
    );
}
