function generateLogs(count: number): ILog[] {
    const servers = ["web-server-01", "web-server-02", "web-server-03", "web-server-04", "web-server-05",
        "db-server-01", "db-server-02", "db-server-03", "cache-server-01", "cache-server-02",
        "api-server-01", "api-server-02", "worker-server-01", "worker-server-02"];
    const apps = ["api-gateway", "payment-service", "database-service", "notification-service",
        "analytics-service", "redis-cache", "user-service", "order-service", "inventory-service",
        "shipping-service", "email-service", "sms-service", "auth-service", "reporting-service"];
    const sourceContexts = ["AuthenticationController", "PaymentProcessor", "DatabaseConnection",
        "RequestHandler", "EmailService", "AnalyticsCollector", "QueryExecutor",
        "UserController", "OrderController", "InventoryManager", "ShippingHandler",
        "NotificationService", "CacheManager", "SessionManager", "RateLimiter",
        "AuditLogger", "SecurityFilter", "ValidationService", null];
    const levels = ["INFO", "WARNING", "ERROR", "DEBUG"];
    const accounts = ["user@example.com", "admin@example.com", "customer@example.com",
        "support@example.com", "analytics@example.com", "system@example.com", null];

    const messages = {
        INFO: [
            "User login successful for account: {account}. The authentication process completed successfully after validating credentials against the identity provider. Session token was generated and stored securely. User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36. IP address: {ip}. Login timestamp: {logTime}. Session duration set to 24 hours. All security checks passed including two-factor authentication verification.",
            "API request processed successfully: {method} {path}. The request was received at {logTime} and processed by the {sourceContext} component. Request ID: {requestId}. Response status: 200 OK. Processing time: {time}ms. Request headers included: Content-Type: application/json, Authorization: Bearer token, User-Agent: API-Client/1.0. Response payload size: {value} bytes. Rate limit remaining: {remaining} requests. Caching strategy applied: cache-control: public, max-age=3600.",
            "Email sent successfully to: {email}. The email message was queued and delivered through the SMTP service provider. Message ID: {id}. Subject: 'Important Notification Regarding Your Account'. Email template used: notification-template-v2. Delivery status: delivered. Bounce rate: 0%. Open tracking enabled. Click tracking enabled. Scheduled delivery time: {logTime}. Email service provider: SendGrid. Delivery latency: {time}ms. Recipient domain validated. SPF, DKIM, and DMARC checks passed.",
            "Analytics event recorded successfully: {event}. Event type: user interaction. Event category: engagement. Event action: {event}. Event label: page_view. User ID: {userId}. Session ID: {id}. Page URL: https://example.com/products/item/{productId}. Referrer: https://google.com/search?q=example. User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7). Screen resolution: 1920x1080. Viewport size: 1440x900. Timestamp: {logTime}. Event properties: {metric}={value}, duration={time}s, scroll_depth=75%. Event stored in analytics database with partition key: {logDay}.",
            "Payment processed successfully: Transaction ID {id}. Payment gateway: Stripe. Payment method: credit_card. Card type: Visa ending in 4242. Amount: $99.99. Currency: USD. Processing fee: $2.90. Net amount: $97.09. Customer ID: {userId}. Order ID: {id}. Payment status: succeeded. Authorization code: AUTH{id}. Transaction timestamp: {logTime}. Payment processor response time: {time}ms. Fraud check: passed. 3D Secure verification: completed. Receipt sent to: {email}. Webhook notification sent to merchant callback URL.",
            "Cache hit for key: {key}. The requested data was successfully retrieved from the Redis cache cluster. Cache key: {key}. Cache server: {server}. Cache hit rate: 95.3%. Data size: {value} bytes. TTL remaining: {time} seconds. Cache layer: L1 (in-memory). Compression: enabled. Serialization format: JSON. Cache region: user-data. Eviction policy: LRU. Memory usage: {percent}%. Cache cluster health: healthy. Response time: {time}ms. Cache version: v2.1.3.",
            "User profile updated successfully: User ID {userId}. Profile changes detected in the following fields: email address, phone number, billing address, notification preferences. Update timestamp: {logTime}. Updated by: {account}. Change tracking enabled. Audit log entry created. Previous values stored for rollback capability. Validation checks passed: email format valid, phone number format valid, address validation passed. Database transaction committed. Cache invalidated for user profile key: user:{userId}:profile. Webhook notification sent to external systems. Profile update confirmation email queued.",
            "Order created successfully: Order ID {id}. Customer ID: {userId}. Order total: $249.99. Items: 3 products. Shipping address: 123 Main St, City, State 12345. Billing address: Same as shipping. Payment method: credit_card. Order status: pending_payment. Created at: {logTime}. Estimated delivery: 5-7 business days. Shipping method: standard. Tax amount: $20.00. Discount applied: 10% off. Order confirmation email sent to: {email}. Inventory reserved for all items. Order tracking number: TRACK{id}. Fulfillment center: warehouse-east-01.",
            "Inventory updated successfully: Product ID {productId}. Stock level changed from 150 to 120 units. Adjustment reason: order fulfillment. Updated by: system. Update timestamp: {logTime}. Warehouse location: warehouse-east-01. SKU: PROD-{productId}. Product name: Sample Product. Category: Electronics. Supplier: Supplier ABC. Reorder point: 50 units. Maximum stock: 500 units. Current stock: 120 units. Stock status: in_stock. Last restocked: 2024-01-10. Inventory value: $12,000.00. Low stock alert: not triggered. Inventory audit log entry created.",
            "Session created successfully for user: {userId}. Session ID: {id}. Session token: JWT token generated with 24-hour expiration. Created at: {logTime}. IP address: {ip}. User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X). Device type: mobile. Browser: Safari. Operating system: iOS 14.0. Session storage: Redis cluster. Session data: user preferences, cart items, recent searches. Security flags: HTTPS enabled, secure cookie flag set, same-site cookie policy: strict. Session activity tracking enabled. Idle timeout: 30 minutes. Maximum session duration: 24 hours.",
            "File uploaded successfully: {filename}. File size: {value} bytes ({percent} MB). File type: PDF document. Upload timestamp: {logTime}. Uploaded by: {account}. Storage location: S3 bucket: production-uploads. Storage path: /uploads/{logDay}/{filename}. File hash: SHA256-{id}. Virus scan: passed. Content validation: passed. File processing: queued. Thumbnail generation: in progress. Metadata extraction: completed. Access permissions: private. CDN distribution: enabled. File URL: https://cdn.example.com/uploads/{filename}. Retention policy: 7 years. Backup: scheduled.",
            "Database backup completed successfully. Backup type: full incremental backup. Backup timestamp: {logTime}. Database: production-db. Backup size: {value} GB. Compression ratio: 70%. Backup duration: {time} minutes. Backup location: S3 bucket: db-backups. Backup path: /backups/{logDay}/full-backup-{id}.tar.gz. Backup verification: passed. Checksum: MD5-{id}. Retention period: 30 days. Replication: enabled to secondary region. Backup encryption: AES-256. Backup status: completed. Next scheduled backup: {logTime}. Backup monitoring: enabled. Alert notifications: configured.",
            "Scheduled task executed successfully: {task}. Task ID: {id}. Execution timestamp: {logTime}. Task type: background job. Task queue: high-priority. Worker node: {server}. Execution duration: {time} seconds. Task status: completed. Result: success. Output: {value} records processed. Error count: 0. Retry count: 0. Task dependencies: all satisfied. Resource usage: CPU {percent}%, Memory {percent}%. Task logs: stored in centralized logging system. Task metrics: recorded. Next execution: scheduled for {logTime}. Task monitoring: active.",
            "Webhook received successfully: {event}. Webhook ID: {id}. Received at: {logTime}. Source: external-service. Event type: {event}. Payload size: {value} bytes. Payload signature: verified. Webhook URL: https://api.example.com/webhooks/{event}. HTTP method: POST. Content-Type: application/json. Response status: 200 OK. Processing time: {time}ms. Event handler: {sourceContext}. Event validation: passed. Event processing: completed. Webhook retry policy: exponential backoff. Maximum retries: 3. Webhook delivery confirmation: sent. Event stored in event log.",
            "Rate limit check passed for IP address: {ip}. Request count: {current} requests. Rate limit: {max} requests per minute. Remaining requests: {remaining}. Reset time: {logTime}. Rate limit window: 60 seconds. Rate limit strategy: sliding window. IP reputation: good. Geographic location: United States. ISP: Example ISP. Rate limit headers: X-RateLimit-Limit: {max}, X-RateLimit-Remaining: {remaining}, X-RateLimit-Reset: {logTime}. Rate limit enforcement: per-IP. Rate limit bypass: not applied. Rate limit monitoring: enabled. Alert threshold: 80%."
        ],
        WARNING: [
            "Payment processing took longer than expected: {time} seconds. Expected processing time: 2 seconds. Actual processing time: {time} seconds. Payment gateway: Stripe. Transaction ID: {id}. Payment method: credit_card. Amount: $99.99. Customer ID: {userId}. Payment status: processing. Delay reason: network latency. Payment gateway response time: {time}ms. Retry attempt: 0. Timeout threshold: 10 seconds. Payment monitoring: active. Alert sent to operations team. Payment queue depth: {current} transactions. Payment processor health: degraded. Recommended action: monitor payment gateway status. Payment will be retried automatically if timeout occurs.",
            "Slow query detected in database: {query}. Query execution time: {time} seconds. Query threshold: 1 second. Database: production-db. Server: {server}. Query type: SELECT. Table: users. Rows examined: {value} rows. Rows returned: {current} rows. Index usage: partial. Query plan: available in slow query log. Query hash: {id}. Connection ID: {id}. User: db_user. Database load: {percent}%. CPU usage: {percent}%. Memory usage: {percent}%. Query optimization: recommended. Index suggestion: consider adding index on created_at column. Query cache: miss. Query monitoring: enabled. Alert threshold: exceeded.",
            "Cache miss detected for key: {key}. Cache lookup failed. Cache server: {server}. Cache region: user-data. Cache key: {key}. Cache miss reason: key expired or not found. TTL: expired. Cache hit rate: {percent}%. Cache miss rate: {percent}%. Data will be fetched from primary data source. Fallback strategy: database query. Query execution time: {time}ms. Data retrieved: {value} bytes. Cache population: in progress. Cache TTL: 3600 seconds. Cache compression: enabled. Cache version: v2.1.3. Cache cluster health: healthy. Cache monitoring: active. Recommended action: review cache key expiration policy.",
            "High memory usage detected on server: {server}. Current memory usage: {percent}%. Memory threshold: 80%. Available memory: {value} MB. Total memory: {max} MB. Memory pressure: high. Memory allocation: {current} MB. Memory fragmentation: {percent}%. Garbage collection: frequent. GC pause time: {time}ms. Memory leak detection: no leaks detected. Process memory: {value} MB. System memory: {value} MB. Swap usage: {percent}%. Memory monitoring: active. Alert sent to operations team. Recommended action: investigate memory-intensive processes. Memory optimization: recommended. Server health: degraded.",
            "Connection pool nearly exhausted on database server: {server}. Active connections: {current}. Maximum connections: {max}. Available connections: {remaining}. Connection pool utilization: {percent}%. Connection pool type: PostgreSQL. Database: production-db. Connection timeout: 30 seconds. Idle connection timeout: 10 minutes. Connection pool health: warning. Long-running queries: {current} queries. Connection wait time: {time}ms. Connection pool monitoring: active. Alert threshold: 80% utilization. Recommended action: increase connection pool size or optimize query performance. Connection pool metrics: recorded. Connection pool alerts: configured.",
            "Retry attempt {attempt} for failed operation. Operation type: external API call. Service: {service}. Operation ID: {id}. Initial failure timestamp: {logTime}. Retry attempt: {attempt}. Maximum retries: 3. Retry strategy: exponential backoff. Retry delay: {time} seconds. Backoff multiplier: 2.0. Operation status: retrying. Previous error: {error}. Error code: 500. Error message: Internal Server Error. Retry timeout: 30 seconds. Circuit breaker: closed. Failure count: {attempt}. Success threshold: 3 consecutive successes. Operation monitoring: active. Alert sent if all retries fail.",
            "Deprecated API endpoint used: {endpoint}. Endpoint: {endpoint}. HTTP method: {method}. Request timestamp: {logTime}. Client IP: {ip}. User agent: API-Client/1.0. API version: v1. Deprecation date: 2024-01-01. Sunset date: 2024-06-01. Replacement endpoint: /api/v2{endpoint}. Migration guide: https://docs.example.com/migration. Deprecation notice: sent in response headers. Warning message: This endpoint is deprecated and will be removed on 2024-06-01. Please migrate to the new endpoint. Client notification: sent. Usage tracking: enabled. Migration status: pending. Support contact: api-support@example.com.",
            "Unusual activity detected for account: {account}. Activity type: multiple failed login attempts. Account: {account}. Failed attempts: {attempt} attempts. Time window: 5 minutes. IP address: {ip}. Geographic location: United States. Device fingerprint: {id}. User agent: Mozilla/5.0. Risk score: {percent}%. Security flags: high. Account status: active. Account lockout: not triggered. Lockout threshold: 5 failed attempts. Security monitoring: active. Alert sent to security team. Recommended action: review account activity. Two-factor authentication: enabled. Account verification: recommended. Security audit log: entry created.",
            "Rate limit approaching for IP address: {ip}. Request count: {current} requests. Rate limit: {max} requests per minute. Remaining requests: {remaining}. Utilization: {percent}%. Reset time: {logTime}. Rate limit window: 60 seconds. Rate limit strategy: sliding window. IP reputation: good. Geographic location: United States. Rate limit headers: X-RateLimit-Limit: {max}, X-RateLimit-Remaining: {remaining}, X-RateLimit-Reset: {logTime}. Rate limit enforcement: per-IP. Warning threshold: 80% utilization. Rate limit monitoring: active. Recommended action: implement request throttling. Rate limit bypass: not available. Client notification: rate limit warning sent in response headers.",
            "Database connection pool size increased automatically. Previous pool size: {current} connections. New pool size: {max} connections. Increase reason: high connection demand. Server: {server}. Database: production-db. Connection pool utilization: {percent}%. Active connections: {current}. Available connections: {remaining}. Connection pool type: PostgreSQL. Auto-scaling: enabled. Scaling threshold: 80% utilization. Scaling cooldown: 5 minutes. Connection pool monitoring: active. Alert sent to operations team. Recommended action: review connection pool configuration. Connection pool metrics: recorded. Connection pool health: healthy. Maximum pool size limit: {max} connections.",
            "Long-running transaction detected in database: {server}. Transaction ID: {id}. Transaction duration: {time} seconds. Transaction threshold: 5 seconds. Database: production-db. Transaction type: UPDATE. Tables affected: users, orders. Rows affected: {value} rows. Transaction isolation level: READ COMMITTED. Lock wait time: {time}ms. Deadlock detection: no deadlocks. Transaction status: active. Connection ID: {id}. User: db_user. Query: {query}. Transaction monitoring: active. Alert sent to database administrators. Recommended action: review transaction logic. Transaction timeout: 30 seconds. Transaction rollback: not triggered. Transaction metrics: recorded.",
            "Missing configuration value detected: {key}. Configuration key: {key}. Configuration file: appsettings.json. Configuration section: Database. Configuration provider: JSON file. Default value: using fallback. Fallback value: localhost. Configuration validation: failed. Configuration monitoring: active. Alert sent to operations team. Recommended action: update configuration file with missing value. Configuration reload: required. Configuration cache: invalidated. Configuration source: file system. Configuration priority: file > environment variables > defaults. Configuration health: degraded. Configuration audit: entry created. Configuration documentation: https://docs.example.com/config.",
            "External service response time high: {time}ms. Service: {service}. Endpoint: /api/data. Expected response time: 200ms. Actual response time: {time}ms. Response time threshold: 500ms. Service health: degraded. Service status: available. Error rate: {percent}%. Timeout rate: {percent}%. Request count: {current} requests. Success rate: {percent}%. Service monitoring: active. Alert sent to operations team. Recommended action: investigate service performance. Service SLA: 99.9% uptime. Service latency: p50={time}ms, p95={time}ms, p99={time}ms. Service dependencies: healthy. Circuit breaker: closed. Retry policy: exponential backoff. Service metrics: recorded."
        ],
        ERROR: [
            "Failed to establish database connection after multiple retry attempts. Database server: {server}. Database: production-db. Connection string: configured. Connection timeout: 30 seconds. Retry attempts: 3 attempts. Retry interval: 5 seconds. Error: System.Data.SqlClient.SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. Connection pool: exhausted. Available connections: 0. Maximum connections: {max}. Active connections: {current}. Connection pool health: critical. Database server status: unknown. Network connectivity: checking. DNS resolution: successful. Port accessibility: checking. Firewall rules: reviewing. Database server logs: analyzing. Recommended action: check database server status and network connectivity. Alert sent to database administrators and operations team. Incident ticket: created. Service impact: high. Affected services: all database-dependent services.",
            "Authentication failed: Invalid credentials provided for account: {account}. Login attempt timestamp: {logTime}. IP address: {ip}. User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64). Authentication method: username/password. Two-factor authentication: not triggered. Account status: active. Account lockout: not triggered. Failed login attempts: {attempt} attempts in last 5 minutes. Account lockout threshold: 5 failed attempts. Security flags: invalid credentials. Risk score: {percent}%. Geographic location: United States. Device fingerprint: {id}. Session creation: denied. Security audit log: entry created. Alert sent to security team. Recommended action: user should reset password if legitimate. Account verification: recommended. Brute force protection: active. Rate limiting: applied.",
            "Payment processing failed: {reason}. Payment gateway: Stripe. Transaction ID: {id}. Payment method: credit_card. Amount: $99.99. Currency: USD. Customer ID: {userId}. Order ID: {id}. Payment status: failed. Failure reason: {reason}. Error code: card_declined. Error message: Your card was declined. Payment gateway response: 402 Payment Required. Payment gateway response time: {time}ms. Retry attempt: {attempt}. Maximum retries: 3. Retry strategy: exponential backoff. Payment queue: payment-failed. Payment notification: sent to customer. Payment webhook: sent to merchant. Payment audit log: entry created. Recommended action: customer should contact their bank or use a different payment method. Payment monitoring: active. Alert sent to payment operations team.",
            "Email delivery failed: {error}. Email service: SendGrid. Message ID: {id}. Recipient: {email}. Subject: Important Notification. Email template: notification-template-v2. Delivery attempt: {attempt}. Maximum retries: 3. Retry interval: 5 minutes. Error: {error}. Error code: 550. Error message: Mailbox unavailable. SMTP response: 550 5.1.1 User unknown. Bounce type: hard bounce. Bounce category: invalid recipient. Email status: failed. Email queue: email-failed. Email notification: sent to sender. Email audit log: entry created. Recommended action: verify recipient email address. Email monitoring: active. Alert sent to email operations team. Email retry: scheduled. Bounce handling: configured. Suppression list: updated.",
            "Database query failed: {query}. Database: production-db. Server: {server}. Query: {query}. Query type: SELECT. Error: System.Data.SqlClient.SqlException: Invalid object name 'nonexistent_table'. Error code: 208. Error severity: 16. Error state: 1. Connection ID: {id}. Transaction ID: {id}. Query execution time: {time}ms. Query plan: not available. Query cache: miss. Database user: db_user. Database schema: public. Table: nonexistent_table. Recommended action: verify table name and schema. Query validation: failed. Query monitoring: active. Alert sent to database administrators. Query audit log: entry created. Query optimization: not applicable. Query retry: not recommended. Database connection: healthy. Query syntax: valid. Table existence: false.",
            "External API call failed: {service}. Service: {service}. Endpoint: /api/data. HTTP method: GET. Request timestamp: {logTime}. Response status: 500 Internal Server Error. Response time: {time}ms. Timeout: 30 seconds. Retry attempt: {attempt}. Maximum retries: 3. Error: System.Net.Http.HttpRequestException: The remote server returned an error: (500) Internal Server Error. Error details: Internal server error occurred while processing request. Request ID: {requestId}. Service health: degraded. Service status: unavailable. Circuit breaker: open. Failure count: {attempt}. Success threshold: 3 consecutive successes. Service monitoring: active. Alert sent to operations team. Recommended action: contact external service provider. Service SLA: 99.9% uptime. Service dependencies: checking. Fallback strategy: using cached data.",
            "File upload failed: {filename}. File name: {filename}. File size: {value} bytes. File type: PDF document. Upload timestamp: {logTime}. Uploaded by: {account}. Storage service: S3. Storage bucket: production-uploads. Error: System.IO.IOException: The network path was not found. Error code: NetworkError. Error message: Failed to connect to S3 storage service. Connection timeout: 30 seconds. Retry attempt: {attempt}. Maximum retries: 3. Storage service health: degraded. Storage service status: unavailable. File validation: passed. Virus scan: not performed. Content validation: passed. File processing: not started. Recommended action: check S3 storage service status and network connectivity. File upload queue: upload-failed. File upload monitoring: active. Alert sent to storage operations team. File upload retry: scheduled.",
            "Session expired for user: {userId}. Session ID: {id}. User ID: {userId}. Session creation time: {logTime}. Session expiration time: {logTime}. Session duration: 24 hours. Session timeout reason: idle timeout exceeded. Idle timeout: 30 minutes. Last activity: {logTime}. Session storage: Redis cluster. Session data: cleared. Session token: invalidated. Security flags: session expired. User notification: session expired message displayed. Session cleanup: completed. Session audit log: entry created. Recommended action: user should log in again. Session monitoring: active. Session security: maintained. Session replay: prevented. Session hijacking: prevented. Session fixation: prevented. Session management: secure.",
            "Invalid request format: {details}. Request ID: {requestId}. Request timestamp: {logTime}. HTTP method: {method}. Request path: {path}. Content-Type: application/json. Request body size: {value} bytes. Error: System.ArgumentException: Invalid request format. Error details: {details}. Validation errors: missing required field 'email', invalid field format 'phone_number'. Request validation: failed. Request schema: not matched. Required fields: email, phone_number, name. Provided fields: name, phone_number. Missing fields: email. Invalid fields: phone_number. Request monitoring: active. Alert sent to API team. Recommended action: client should fix request format according to API documentation. API documentation: https://docs.example.com/api. Request audit log: entry created. Request rejection: 400 Bad Request.",
            "Authorization failed: Insufficient permissions for user: {account}. User ID: {userId}. Requested resource: {path}. Required permission: admin_access. User permissions: user_read, user_write. Permission check: failed. Authorization method: role-based access control (RBAC). User role: user. Required role: administrator. Access control list: checked. Permission matrix: reviewed. Security audit log: entry created. Recommended action: user should contact administrator for access. Authorization monitoring: active. Alert sent to security team. Access attempt: logged. Security flags: unauthorized access attempt. Risk score: {percent}%. IP address: {ip}. Geographic location: United States. Device fingerprint: {id}. Session: terminated.",
            "Database transaction rolled back due to error. Transaction ID: {id}. Database: production-db. Server: {server}. Transaction type: UPDATE. Tables affected: users, orders. Rows affected: {value} rows before rollback. Transaction duration: {time} seconds. Rollback reason: constraint violation. Error: System.Data.SqlClient.SqlException: The UPDATE statement conflicted with the FOREIGN KEY constraint. Error code: 547. Error severity: 16. Error state: 0. Constraint: FK_Orders_Users. Constraint violation: attempted to update user_id to non-existent value. Transaction isolation level: READ COMMITTED. Lock wait time: {time}ms. Deadlock detection: no deadlocks. Transaction status: rolled back. Data consistency: maintained. Transaction audit log: entry created. Recommended action: fix data integrity issue. Transaction monitoring: active. Alert sent to database administrators.",
            "Cache connection lost to Redis cluster. Cache server: {server}. Cache cluster: production-cache. Connection type: Redis. Connection timeout: 5 seconds. Retry attempts: 3 attempts. Retry interval: 1 second. Error: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it. Error code: ConnectionRefused. Cache cluster health: degraded. Cache cluster status: partially available. Available cache nodes: {current} nodes. Total cache nodes: {max} nodes. Cache failover: in progress. Cache data: may be stale. Cache fallback: database queries. Cache monitoring: active. Alert sent to cache operations team. Recommended action: check Redis cluster status and network connectivity. Cache connection pool: reset. Cache reconnection: automatic. Cache health check: scheduled.",
            "Webhook delivery failed: {url}. Webhook ID: {id}. Webhook URL: {url}. Event type: {event}. Payload size: {value} bytes. Delivery attempt: {attempt}. Maximum retries: 3. Retry interval: 5 minutes. Error: System.Net.Http.HttpRequestException: The remote server returned an error: (404) Not Found. Error code: 404. Error message: Webhook endpoint not found. HTTP response: 404 Not Found. Webhook signature: valid. Webhook timestamp: {logTime}. Webhook retry policy: exponential backoff. Webhook queue: webhook-failed. Webhook monitoring: active. Alert sent to webhook operations team. Recommended action: verify webhook URL is correct and endpoint is available. Webhook audit log: entry created. Webhook retry: scheduled. Webhook delivery confirmation: not received. Webhook status: failed.",
            "Rate limit exceeded for IP address: {ip}. Request count: {current} requests. Rate limit: {max} requests per minute. Exceeded by: {current} requests. Rate limit window: 60 seconds. Rate limit strategy: sliding window. IP reputation: good. Geographic location: United States. Rate limit enforcement: per-IP. Rate limit bypass: not available. Rate limit headers: X-RateLimit-Limit: {max}, X-RateLimit-Remaining: 0, X-RateLimit-Reset: {logTime}. HTTP response: 429 Too Many Requests. Retry-After header: {time} seconds. Rate limit monitoring: active. Alert sent to operations team. Recommended action: client should implement request throttling. Rate limit documentation: https://docs.example.com/rate-limits. Rate limit audit log: entry created. Rate limit violation: logged.",
            "Configuration validation failed during application startup. Configuration file: appsettings.json. Configuration section: Database. Validation errors: invalid connection string format, missing required setting 'ConnectionTimeout', invalid value for 'MaxPoolSize': must be between 10 and 100. Configuration provider: JSON file. Configuration validation: failed. Application startup: aborted. Configuration health: critical. Configuration monitoring: active. Alert sent to operations team. Recommended action: fix configuration file according to validation rules. Configuration documentation: https://docs.example.com/config. Configuration audit: entry created. Configuration reload: required. Configuration cache: invalidated. Application status: not started. Service impact: high. Affected services: all services. Configuration validation rules: documented. Configuration schema: JSON schema validation."
        ],
        DEBUG: [
            "Cache hit for key: {key} in Redis cache cluster. Cache key: {key}. Cache server: {server}. Cache region: user-data. Cache hit rate: 95.3%. Data size: {value} bytes. TTL remaining: {time} seconds. Cache layer: L1 (in-memory). Compression: enabled. Serialization format: JSON. Cache version: v2.1.3. Cache cluster health: healthy. Response time: {time}ms. Cache statistics: hits={current}, misses={remaining}, hit_rate={percent}%. Cache eviction policy: LRU. Memory usage: {percent}%. Cache monitoring: active. Cache metrics: recorded. Cache performance: optimal.",
            "Request received: {method} {path} at {logTime}. Request ID: {requestId}. Client IP: {ip}. User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36. Request headers: Content-Type: application/json, Authorization: Bearer token, Accept: application/json. Request body size: {value} bytes. Request validation: in progress. Request routing: determined. Request handler: {sourceContext}. Request middleware: authentication, authorization, logging, rate limiting. Request processing: started. Request metrics: recorded. Request tracking: enabled. Request audit: logged. Request performance: monitoring. Request timeout: 30 seconds. Request priority: normal.",
            "Query executed: {query} on database: production-db. Query type: SELECT. Query execution time: {time}ms. Rows examined: {value} rows. Rows returned: {current} rows. Index usage: primary key index. Query plan: available. Query cache: hit. Query hash: {id}. Connection ID: {id}. Database user: db_user. Query optimization: applied. Query statistics: recorded. Query monitoring: active. Query performance: optimal. Query lock wait time: 0ms. Query deadlock: none. Query transaction: committed. Query result: cached. Query metrics: recorded.",
            "Cache miss for key: {key} in Redis cache cluster. Cache key: {key}. Cache server: {server}. Cache region: user-data. Cache miss reason: key not found. Cache hit rate: 95.3%. Cache miss rate: 4.7%. Data will be fetched from primary data source. Fallback strategy: database query. Query execution time: {time}ms. Data retrieved: {value} bytes. Cache population: in progress. Cache TTL: 3600 seconds. Cache compression: enabled. Cache version: v2.1.3. Cache cluster health: healthy. Cache statistics: hits={current}, misses={remaining}, hit_rate={percent}%. Cache monitoring: active. Cache metrics: recorded.",
            "Session validated for user: {userId}. Session ID: {id}. User ID: {userId}. Session token: JWT token validated. Token signature: valid. Token expiration: not expired. Token issuer: verified. Token audience: verified. Session storage: Redis cluster. Session data: retrieved. Session activity: updated. Last activity: {logTime}. Session timeout: 30 minutes. Session duration: 24 hours. Session security: validated. Session flags: active, authenticated, authorized. Session monitoring: active. Session metrics: recorded. Session performance: optimal.",
            "Rate limit check performed for IP address: {ip}. Request count: {current} requests. Rate limit: {max} requests per minute. Remaining requests: {remaining}. Rate limit window: 60 seconds. Rate limit strategy: sliding window. IP reputation: good. Rate limit headers: X-RateLimit-Limit: {max}, X-RateLimit-Remaining: {remaining}, X-RateLimit-Reset: {logTime}. Rate limit enforcement: per-IP. Rate limit check: passed. Rate limit monitoring: active. Rate limit metrics: recorded. Rate limit performance: optimal.",
            "Database connection acquired from connection pool. Connection pool: production-db. Server: {server}. Active connections: {current}. Available connections: {remaining}. Maximum connections: {max}. Connection pool utilization: {percent}%. Connection ID: {id}. Connection timeout: 30 seconds. Idle connection timeout: 10 minutes. Connection pool health: healthy. Connection acquisition time: {time}ms. Connection pool statistics: recorded. Connection pool monitoring: active. Connection pool performance: optimal.",
            "Validation passed for request: {requestId}. Request ID: {requestId}. Request timestamp: {logTime}. Validation type: schema validation. Validation rules: applied. Required fields: validated. Field formats: validated. Field types: validated. Field constraints: validated. Validation errors: none. Validation duration: {time}ms. Validation performance: optimal. Validation monitoring: active. Validation metrics: recorded. Request status: validated. Request processing: continued.",
            "Middleware executed: {middleware} for request: {requestId}. Middleware: {middleware}. Request ID: {requestId}. Execution order: determined. Execution time: {time}ms. Middleware status: completed. Middleware errors: none. Middleware performance: optimal. Middleware monitoring: active. Middleware metrics: recorded. Request context: updated. Request processing: continued. Middleware chain: proceeding.",
            "Background job queued: {job} in job queue. Job ID: {id}. Job type: {job}. Job queue: high-priority. Job priority: normal. Job payload: {value} bytes. Job scheduling: immediate. Job retry policy: exponential backoff. Maximum retries: 3. Job timeout: 30 minutes. Job dependencies: none. Job status: queued. Job monitoring: active. Job metrics: recorded. Job performance: optimal. Job processing: scheduled.",
            "Configuration loaded: {config} from configuration provider. Configuration key: {config}. Configuration value: loaded. Configuration source: JSON file. Configuration provider: JSON file provider. Configuration priority: file > environment variables > defaults. Configuration validation: passed. Configuration cache: updated. Configuration reload: not required. Configuration monitoring: active. Configuration metrics: recorded. Configuration performance: optimal.",
            "Health check passed for service: {server}. Service: {server}. Health check type: liveness probe. Health check endpoint: /health. Health check response: 200 OK. Health check duration: {time}ms. Service status: healthy. Service dependencies: healthy. Database connectivity: healthy. Cache connectivity: healthy. External services: healthy. Service metrics: CPU {percent}%, Memory {percent}%. Service performance: optimal. Health check monitoring: active. Health check metrics: recorded.",
            "Metrics collected: {metric}={value} for monitoring system. Metric name: {metric}. Metric value: {value}. Metric type: gauge. Metric timestamp: {logTime}. Metric tags: server={server}, app={app}. Metric aggregation: sum. Metric retention: 30 days. Metric storage: time-series database. Metric query: available. Metric alerting: configured. Metric monitoring: active. Metric performance: optimal. Metric collection: successful."
        ]
    };

    const exceptions = [
        "System.Data.SqlClient.SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.",
        "UnauthorizedAccessException: Invalid username or password provided",
        "System.Net.Http.HttpRequestException: The remote server returned an error: (500) Internal Server Error.",
        "System.ArgumentNullException: Value cannot be null. Parameter name: {param}",
        "System.InvalidOperationException: The operation is not valid for the current state of the object.",
        "System.TimeoutException: The operation has timed out.",
        "System.IO.IOException: The network path was not found.",
        "System.UnauthorizedAccessException: Access is denied.",
        "System.ArgumentException: An item with the same key has already been added.",
        "System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.",
        null, null, null, null, null, null, null, null, null, null
    ];

    const logs: ILog[] = [];
    const startDate = new Date("2024-01-01T00:00:00Z");

    for (let i = 0; i < count; i++) {
        const logDay = Math.floor(Math.random() * 31) + 1;
        const hours = Math.floor(Math.random() * 24);
        const minutes = Math.floor(Math.random() * 60);
        const seconds = Math.floor(Math.random() * 60);
        const milliseconds = Math.floor(Math.random() * 1000);

        const logDate = new Date(startDate);
        logDate.setDate(logDay);
        logDate.setHours(hours, minutes, seconds, milliseconds);

        const server = servers[Math.floor(Math.random() * servers.length)];
        const app = apps[Math.floor(Math.random() * apps.length)];
        const sourceContext = sourceContexts[Math.floor(Math.random() * sourceContexts.length)];
        const level = levels[Math.floor(Math.random() * levels.length)];
        const account = accounts[Math.floor(Math.random() * accounts.length)];

        const levelMessages = messages[level as keyof typeof messages];
        let message = levelMessages[Math.floor(Math.random() * levelMessages.length)];

        // Replace placeholders in messages
        message = message.replace("{account}", account || "unknown");
        message = message.replace("{method}", ["GET", "POST", "PUT", "DELETE", "PATCH"][Math.floor(Math.random() * 5)]);
        message = message.replace("{path}", ["/api/users", "/api/orders", "/api/products", "/api/payments", "/api/auth"][Math.floor(Math.random() * 5)]);
        message = message.replace("{email}", `user${Math.floor(Math.random() * 1000)}@example.com`);
        message = message.replace("{event}", ["page_view", "click", "purchase", "login", "logout"][Math.floor(Math.random() * 5)]);
        message = message.replace("{id}", String(Math.floor(Math.random() * 100000)));
        message = message.replace("{key}", `key:${Math.floor(Math.random() * 1000)}`);
        message = message.replace("{userId}", String(Math.floor(Math.random() * 10000)));
        message = message.replace("{productId}", String(Math.floor(Math.random() * 1000)));
        message = message.replace("{filename}", `file${Math.floor(Math.random() * 100)}.pdf`);
        message = message.replace("{task}", ["backup", "cleanup", "report", "sync"][Math.floor(Math.random() * 4)]);
        message = message.replace("{ip}", `${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`);
        message = message.replace("{time}", (Math.random() * 10).toFixed(2));
        message = message.replace("{query}", "SELECT * FROM users WHERE id = ?");
        message = message.replace("{percent}", String(Math.floor(Math.random() * 30) + 70));
        message = message.replace("{current}", String(Math.floor(Math.random() * 50) + 10));
        message = message.replace("{max}", "100");
        message = message.replace("{attempt}", String(Math.floor(Math.random() * 3) + 1));
        message = message.replace("{endpoint}", "/api/v1/deprecated");
        message = message.replace("{reason}", "Insufficient funds");
        message = message.replace("{error}", "SMTP connection failed");
        message = message.replace("{service}", ["payment-gateway", "email-provider", "sms-provider"][Math.floor(Math.random() * 3)]);
        message = message.replace("{details}", "Missing required field: email");
        message = message.replace("{url}", "https://webhook.example.com/callback");
        message = message.replace("{requestId}", `req-${Math.floor(Math.random() * 100000)}`);
        message = message.replace("{middleware}", ["auth", "logging", "cors", "rate-limit"][Math.floor(Math.random() * 4)]);
        message = message.replace("{job}", ["process-payment", "send-email", "generate-report"][Math.floor(Math.random() * 3)]);
        message = message.replace("{config}", "database.connection");
        message = message.replace("{metric}", ["cpu", "memory", "requests"][Math.floor(Math.random() * 3)]);
        message = message.replace("{value}", String(Math.floor(Math.random() * 100)));
        message = message.replace("{remaining}", String(Math.floor(Math.random() * 100)));
        message = message.replace("{param}", "userId");

        const exception = level === "ERROR"
            ? exceptions[Math.floor(Math.random() * exceptions.length)]
            : null;

        logs.push({
            id: i + 1,
            logTime: logDate.toISOString(),
            logDay,
            server,
            app,
            sourceContext,
            level,
            message,
            exception,
            account
        });
    }

    return logs;
}

const sampleLogs: ILog[] = generateLogs(500);

export const logResponse: IPagedList<ILog> = {
    items: sampleLogs,
    pageNumber: 1,
    pageSize: 50,
    totalCount: 500,
    hasNextPage: true,
    hasPreviousPage: false
};

export interface IPagedList<T> {
    items: T[];
    pageNumber: number;
    pageSize: number;
    totalCount: number | null;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
}

export interface ILog {
    id: number;
    logTime: string;
    logDay: number;
    server: string;
    app: string;
    sourceContext: string | null;
    level: string;
    message: string;
    exception: string | null;
    account: string | null;
}